[package]
name = "streamer"
version = "0.1.0"
edition = "2021"

[dependencies]
# actix-web = "4"
# actix-ws = "0.3.0"
cpal = "0.15.3"
anyhow = "1.0.86"
ctrlc = "3.4.4"
tungstenite = "0.23.0"
serde = {version = "1.0.208", features = ["derive"]}
serde_json = "1.0.125"
